Lambda School Data Science

*Unit 2, Sprint 3, Module 2*

---


# Wrangle ML datasets

- [ ] Continue to clean and explore your data. 
- [ ] For the evaluation metric you chose, what score would you get just by guessing?
- [ ] Can you make a fast, first model that beats guessing?

**We recommend that you use your portfolio project dataset for all assignments this sprint.**

**But if you aren't ready yet, or you want more practice, then use the New York City property sales dataset for today's assignment.** Follow the instructions below, to just keep a subset for the Tribeca neighborhood, and remove outliers or dirty data. [Here's a video walkthrough](https://youtu.be/pPWFw8UtBVg?t=584) you can refer to if you get stuck or want hints!

- Data Source: [NYC OpenData: NYC Citywide Rolling Calendar Sales](https://data.cityofnewyork.us/dataset/NYC-Citywide-Rolling-Calendar-Sales/usep-8jbt)
- Glossary: [NYC Department of Finance: Rolling Sales Data](https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page)

In [106]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = ''
    !pip install category_encoders==2.*
    !pip install pandas-profiling==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [107]:
# Read New York City property sales data
import pandas as pd
df = pd.read_csv(DATA_PATH+'condos/NYC_Citywide_Rolling_Calendar_Sales.csv')

Your code starts here:

In [108]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,1,CHELSEA,13 CONDOS - ELEVATOR APARTMENTS,2,716,1246,NaN,R4,"447 WEST 18TH STREET, PH12A",PH12A,...,1.0,0.0,1.0,"10,733",1979.0,2007.0,2,R4,$ - 0,01/01/2019
1,1,FASHION,21 OFFICE BUILDINGS,4,812,68,NaN,O5,144 WEST 37TH STREET,NaN,...,0.0,6.0,6.0,"2,962",15435.0,1920.0,4,O5,$ - 0,01/01/2019
2,1,FASHION,21 OFFICE BUILDINGS,4,839,69,NaN,O5,40 WEST 38TH STREET,NaN,...,0.0,7.0,7.0,"2,074",11332.0,1930.0,4,O5,$ - 0,01/01/2019
3,1,GREENWICH VILLAGE-WEST,13 CONDOS - ELEVATOR APARTMENTS,2,592,1041,NaN,R4,"1 SHERIDAN SQUARE, 8C",8C,...,1.0,0.0,1.0,0,500.0,0.0,2,R4,$ - 0,01/01/2019
4,1,UPPER EAST SIDE (59-79),15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,1379,1402,NaN,R1,"20 EAST 65TH STREET, B",B,...,1.0,0.0,1.0,0,6406.0,0.0,2,R1,$ - 0,01/01/2019

In [109]:
df.shape

(23040, 21)

In [110]:
# Change column names: replace spaces with underscores
df.columns =['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AT_PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING_CLASS_AT_PRESENT', 'ADDRESS', 'APARTMENT_NUMBER', 'ZIP_CODE',
       'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE']

In [111]:
# Get Pandas Profiling Report
from pandas_profiling import ProfileReport

ProfileReport(df)

Summarize dataset:   0%|          | 0/34 [00:00<?, ?it/s]

KeyboardInterrupt:

In [112]:
# Keep just the subset of data for the Tribeca neighborhood
# Check how many rows you have now. (Should go down from > 20k rows to 146)
df_sub= df[df['NEIGHBORHOOD']=='TRIBECA']
df_sub.shape

(146, 21)

In [113]:
# Q. What's the date range of these property sales in Tribeca?
print(df_sub['SALE_DATE'].min())
df_sub['SALE_DATE'].max()

01/03/2019

'04/30/2019'

In [120]:
# The Pandas Profiling Report showed that SALE_PRICE was read as strings
# Convert it to integers
df_sub['SALE_PRICE'] = df_sub['SALE_PRICE'].str.replace("-","")
df_sub['SALE_PRICE'] = df_sub['SALE_PRICE'].str.replace("$","")
df_sub['SALE_PRICE'] = df_sub['SALE_PRICE'].str.replace(",","",regex=True)
df_sub['SALE_PRICE'] = df_sub['SALE_PRICE'].astype(int)

C:\Users\arnel\anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\arnel\anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.
C:\Users\arnel\anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\arnel\anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\arnel\anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [121]:
# Q. What is the maximum SALE_PRICE in this dataset?
df_sub['SALE_PRICE'].max()

260000000

In [123]:
# Look at the row with the max SALE_PRICE
df_sub

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,EASE-MENT,BUILDING_CLASS_AT_PRESENT,ADDRESS,APARTMENT_NUMBER,...,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE
220,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,222,1013,NaN,R4,"181 HUDSON STREET, 6D",6D,...,1.0,0.0,1.0,"7,878",1840.0,1909.0,2,R4,2800000,01/03/2019
763,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,16,9022,NaN,R4,"10 LITTLE WEST STREET, 19A",19A,...,1.0,0.0,1.0,0,1759.0,0.0,2,R4,2650000,01/07/2019
996,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,212,1404,NaN,R4,"11 BEACH STREET, 1D",1D,...,1.0,0.0,1.0,"11,213",2651.0,1900.0,2,R4,0,01/08/2019
1276,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,16,1441,NaN,R4,"30 LITTLE WEST STREET, 7G",7G,...,1.0,0.0,1.0,0,1190.0,2005.0,2,R4,1005000,01/09/2019
1542,1,TRIBECA,02 TWO FAMILY DWELLINGS,1,132,26,NaN,S2,"75 WARREN STREET, XX",NaN,...,2.0,1.0,3.0,"1,819",10117.0,1905.0,1,S2,12950000,01/10/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22221,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,222,1206,NaN,R4,"443 GREENWICH STREET, 1F",1F,...,1.0,0.0,1.0,"35,127",2429.0,1905.0,2,R4,5761259,04/24/2019
22732,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,16,1806,NaN,R4,"70 LITTLE WEST STREET, 11K",11K,...,1.0,0.0,1.0,0,1601.0,2006.0,2,R4,2600000,04/29/2019
22733,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,16,8071,NaN,R4,"2 SOUTH END AVENUE, 5G",5G,...,1.0,0.0,1.0,0,634.0,1990.0,2,R4,605000,04/29/2019
22897,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,16,8132,NaN,R4,"2 SOUTH END AVENUE, 8B",8B,...,1.0,0.0,1.0,0,939.0,1990.0,2,R4,960000,04/30/2019
22898,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,140,1162,NaN,R4,"311 GREENWICH ST, 8B",8B,...,1.0,0.0,1.0,"9,900",695.0,0.0,2,R4,975000,04/30/2019

In [ ]:
# Get value counts of TOTAL_UNITS
# Q. How many property sales were for multiple units?

In [ ]:
# Keep only the single units

In [ ]:
# Q. Now what is the max sales price? How many square feet does it have?

In [ ]:
# Q. How often did $0 sales occur in this subset of the data?

# There's a glossary here: 
# https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page

# It says:
# A $0 sale indicates that there was a transfer of ownership without a 
# cash consideration. There can be a number of reasons for a $0 sale including 
# transfers of ownership from parents to children.

In [ ]:
# Look at property sales for > 5,000 square feet
# Q. What is the highest square footage you see?

In [ ]:
# What are the building class categories?
# How frequently does each occur?

In [ ]:
# Keep subset of rows:
# Sale price more than $0, 
# Building class category = Condos - Elevator Apartments

# Check how many rows you have now. (Should be 106 rows.)

In [ ]:
# Make a Plotly Express scatter plot of GROSS_SQUARE_FEET vs SALE_PRICE

In [ ]:
# Add an OLS (Ordinary Least Squares) trendline,
# to see how the outliers influence the "line of best fit"

In [ ]:
# Look at sales for more than $35 million

# All are at 70 Vestry Street
# All but one have the same SALE_PRICE & SALE_DATE
# Was the SALE_PRICE for each? Or in total?
# Is this dirty data?

In [ ]:
# Make a judgment call:
# Keep rows where sale price was < $35 million

# Check how many rows you have now. (Should be down to 90 rows.)

In [ ]:
# Now that you've removed outliers,
# Look again at a scatter plot with OLS (Ordinary Least Squares) trendline

In [ ]:
# Select these columns, then write to a csv file named tribeca.csv. Don't include the index.